title: Docker
version: "1.0"
requirements:
  - homePage: https://www.docker.com/
    which: docker
rootItems:
  - script: list-containers
    title: List Containers
scripts:
  list-containers:
    command: |
      docker ps --all --format '{{ json . }}' | sunbeam query '
      {
        title: .Names,
        subtitle: .Image,
        accessories: [ .State ],
        actions: [
          {type: "run-script", title: "Open Shell", script: "exec-command", "with": {"container": .Names, "command": "bash"}}
        ]
      }
      '
    mode: filter
  exec-command:
    command: |
      docker exec -it ${{ container }} ${{ command }} | less
    mode: command
    params:
      - name: container
        type: textfield
        title: Command
      - name: command
        type: textfield
        title: Command
