# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
changelog:
  skip: true
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
      - android
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: sunbeam
    homepage: https://pomdtr.github.io/sunbeam
    tap:
      owner: pomdtr
      name: homebrew-tap
scoop:
  bucket:
    owner: pomdtr
    name: scoop-bucket
  folder: bucket
  homepage: https://pomdtr.github.io/sunbeam
  description: Generate powerful UIs from simple scripts written in any language.
  license: MIT
