# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run . completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run . completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run . completion "fish" >./completions/{{ .ProjectName }}.fish'
changelog:
  skip: true
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE-MIT
      - completions/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: sunbeam
    homepage: https://pomdtr.github.io/sunbeam
    tap:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "sunbeam"
      bash_completion.install "completions/sunbeam.bash"
      zsh_completion.install "completions/sunbeam.zsh"
      fish_completion.install "completions/sunbeam.fish"
scoop:
  bucket:
    owner: pomdtr
    name: scoop-bucket
  folder: bucket
  homepage: https://pomdtr.github.io/sunbeam
  description: Generate powerful UIs from simple scripts written in any language.
  license: MIT
