# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run ./cmd/sunbeam/main.go completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run ./cmd/sunbeam/main.go completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run ./cmd/sunbeam/main.go completion "fish" >./completions/{{ .ProjectName }}.fish'
changelog:
  skip: true
builds:
  - main: ./cmd/sunbeam/main.go
    binary: sunbeam
    ldflags:
      - s -w
      - -X github.com/pomdtr/sunbeam/internal/cli.Version={{.Version}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  - name_template: "{{ .Binary }}-{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE-MIT
      - completions/*
checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  extra_files:
    - glob: internal/schemas/config.schema.json

snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: sunbeam
    homepage: https://pomdtr.github.io/sunbeam
    repository:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "sunbeam"
      bash_completion.install "completions/sunbeam.bash"
      zsh_completion.install "completions/sunbeam.zsh"
      fish_completion.install "completions/sunbeam.fish"
