# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run . completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run . completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run . completion "fish" >./completions/{{ .ProjectName }}.fish'
changelog:
  skip: true
builds:
  - ldflags:
      - -s -w -X github.com/pomdtr/sunbeam/cmd.Version={{.Version}} -X github.com/pomdtr/sunbeam/cmd.Date={{time "2006-01-02"}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - name_template: "{{ .Binary }}-{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE-MIT
      - completions/*
checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  extra_files:
    - glob: pkg/schemas/config.schema.json

snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: sunbeam
    homepage: https://pomdtr.github.io/sunbeam
    repository:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "sunbeam"
      bash_completion.install "completions/sunbeam.bash"
      zsh_completion.install "completions/sunbeam.zsh"
      fish_completion.install "completions/sunbeam.fish"
