[book]
title = "Sunbeam Documentation"
description = "Generate complex TUIs from simple scripts written in any language."
authors = ["Achille Lacoin"]
language = "en"
src = "docs"

[output.html]
git-repository-url = "https://github.com/pomdtr/sunbeam"
edit-url-template = "https://github.com/pomdtr/sunbeam/edit/main/{path}"
