on: [push]
name: Test Extensions
jobs:
  test-tldr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Install tldr
        run: |
          curl -L https://github.com/dbrgn/tealdeer/releases/download/v1.6.1/tealdeer-linux-x86_64-musl -o /usr/local/bin/tldr
          chmod +x /usr/local/bin/tldr
      - run: |
          go build -o sunbeam
      - run: |
          tldr --update
          ./docs/examples/tldr/sunbeam-extension | ./sunbeam validate
