name: Build and Deploy Website
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.16
      - name: Generate CLI docs
        run: go run main.go docs > website/frontend/docs/reference/cli.md
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache-dependency-path: website/frontend/package-lock.json
      - name: Build website
        working-directory: website/frontend
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read
    steps:
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: sunbeam # the name of the project on Deno Deploy
          root: website
          entrypoint: main.ts # the entrypoint to deploy
