name: Build and Deploy Website
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Generate CLI docs
        run: go run ./cmd/sunbeam/main.go docs > website/frontend/docs/reference/cli.md
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache-dependency-path: website/frontend/package-lock.json
      - name: Install Node dependencies
        working-directory: website/frontend
        run: npm install
      - name: Build website
        working-directory: website/frontend
        run: npm run build
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: sunbeam # the name of the project on Deno Deploy
          root: website
          entrypoint: main.ts # the entrypoint to deploy
